/*
 * Author Roger G. Coscojuela
 */
package domino.vista;

import domino.controlador.ControladorGrafic;
import static java.lang.System.err;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Roger G. Coscojuela
 */
public class Config extends javax.swing.JFrame {

    String[] jugadors;
    ControladorGrafic control;

    /**
     * Creates new form Config
     */
    public Config() {
        initComponents();
    }

    public Config(ControladorGrafic control) {
        initComponents();
        this.control = control;
        btNoms.addActionListener(control);
        if (jRB2Jug.isSelected()) {
            etJugador3.setVisible(false);
            etJugador4.setVisible(false);
            jLabelJugador3.setVisible(false);
            jLabelJugador4.setVisible(false);
        }

    }

    public String[] getJugadors() {
        if (jRB4Jug.isSelected()) {
            jugadors = new String[4];
            jugadors[0] = etJugador1.getText();
            jugadors[1] = etJugador2.getText();
            jugadors[2] = etJugador3.getText();
            jugadors[3] = etJugador4.getText();
        } else {
            jugadors = new String[2];
            jugadors[0] = etJugador1.getText();
            jugadors[1] = etJugador2.getText();

        }
        return jugadors;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jRB4Jug = new javax.swing.JRadioButton();
        jRB2Jug = new javax.swing.JRadioButton();
        jLabelJugador1 = new javax.swing.JLabel();
        jLabelJugador2 = new javax.swing.JLabel();
        jLabelJugador3 = new javax.swing.JLabel();
        jLabelJugador4 = new javax.swing.JLabel();
        etJugador1 = new javax.swing.JTextField();
        etJugador2 = new javax.swing.JTextField();
        etJugador3 = new javax.swing.JTextField();
        etJugador4 = new javax.swing.JTextField();
        btNoms = new javax.swing.JButton();
        jCBIa = new javax.swing.JCheckBox();
        jCBVeureFitxes = new javax.swing.JCheckBox();

        buttonGroup1.add(jRB4Jug);
        jRB4Jug.setText("4 Jugadors");
        jRB4Jug.setActionCommand("4Jugadors");
        jRB4Jug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBJugActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRB2Jug);
        jRB2Jug.setSelected(true);
        jRB2Jug.setText("2 Jugadors");
        jRB2Jug.setActionCommand("2Jugadors");
        jRB2Jug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBJugActionPerformed(evt);
            }
        });

        jLabelJugador1.setText("Nom Jugador 1");

        jLabelJugador2.setText("Nom Jugador 2");

        jLabelJugador3.setText("Nom Jugador 3");

        jLabelJugador4.setText("Nom Jugador 4");

        etJugador1.setText("Jugador 1");

        etJugador2.setText("Jugador 2");

        etJugador3.setText("Jugador 3");
        etJugador3.setToolTipText("");

        etJugador4.setText("Jugador 4");

        btNoms.setText("Jugar!");
        btNoms.setActionCommand("btNoms");
        btNoms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btJugarActionPerformed(evt);
            }
        });

        jCBIa.setText("IA");
        jCBIa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBActionPerformed(evt);
            }
        });

        jCBVeureFitxes.setSelected(true);
        jCBVeureFitxes.setText("Veure Fitxes Tots Jugadors");
        jCBVeureFitxes.setActionCommand("veureFitxes");
        jCBVeureFitxes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(btNoms))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabelJugador2)
                                        .addComponent(jLabelJugador3)
                                        .addComponent(jLabelJugador4))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(etJugador4, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                                        .addComponent(etJugador3)
                                        .addComponent(etJugador2, javax.swing.GroupLayout.Alignment.TRAILING)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabelJugador1)
                                    .addGap(39, 39, 39)
                                    .addComponent(etJugador1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRB2Jug)
                                    .addComponent(jRB4Jug))
                                .addGap(88, 88, 88)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCBIa)
                                    .addComponent(jCBVeureFitxes))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRB2Jug)
                    .addComponent(jCBVeureFitxes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRB4Jug)
                    .addComponent(jCBIa))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelJugador1)
                    .addComponent(etJugador1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelJugador2)
                    .addComponent(etJugador2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelJugador3)
                    .addComponent(etJugador3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelJugador4)
                    .addComponent(etJugador4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btNoms)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btJugarActionPerformed
        boolean ok = false;
        if (jRB4Jug.isSelected()) {
            if (("".equals(etJugador1.getText())) || "".equals(etJugador2.getText()) || "".equals(etJugador3.getText()) || "".equals(etJugador4.getText())) {
                JOptionPane.showMessageDialog(this, "Es obligatori omplir el nom dels jugadors");
            } else {
                ok = true;
            }
        } else {
            if ("".equals(etJugador1.getText()) || "".equals(etJugador2.getText())) {
                JOptionPane.showMessageDialog(this, "Es obligatori omplir el nom dels jugadors");
            } else {
                ok = true;
            }
        }
        if (ok) {
            this.setVisible(false);
        }
    }//GEN-LAST:event_btJugarActionPerformed

    public boolean getIA() {
        return jCBIa.isSelected();
    }

    public boolean getMostrarFitxes() {
        return jCBVeureFitxes.isSelected();
    }

    private void jRBJugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBJugActionPerformed
        if (evt.getActionCommand().equals("2Jugadors")) {
            Logger.getLogger(getClass().getName()).log(
                    Level.CONFIG, "2 jugadors", err);
            etJugador3.setVisible(false);
            etJugador4.setVisible(false);
            jLabelJugador3.setVisible(false);
            jLabelJugador4.setVisible(false);
        }
        if (evt.getActionCommand().equals("4Jugadors")) {
            Logger.getLogger(getClass().getName()).log(
                    Level.CONFIG, "4 jugadors", err);
            etJugador3.setVisible(true);
            etJugador4.setVisible(true);
            jLabelJugador3.setVisible(true);
            jLabelJugador4.setVisible(true);

        }
    }//GEN-LAST:event_jRBJugActionPerformed

    private void jCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBActionPerformed

        if ("IA".equals(evt.getActionCommand())) {
            System.out.println("Checkbox IA pulsat");
            if (jCBIa.isSelected() == false && jCBVeureFitxes.isSelected() == false) {
                JOptionPane.showMessageDialog(this, "IA desactivada, controlaras a todos los jugadores");
                this.jCBVeureFitxes.setSelected(true);
            }
        }
        if ("veureFitxes".equals(evt.getActionCommand())) {
            System.out.println("Checkbox Veure Fitxes pulsat");
            if (jCBIa.isSelected() == false) {
                JOptionPane.showMessageDialog(this, "IA desactivada, por lo que debes ver las fichas de todos los jugadores.");
                this.jCBVeureFitxes.setSelected(true);
            }
        }
    }//GEN-LAST:event_jCBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Config.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Config.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Config.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Config.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Config().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btNoms;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField etJugador1;
    private javax.swing.JTextField etJugador2;
    private javax.swing.JTextField etJugador3;
    private javax.swing.JTextField etJugador4;
    private javax.swing.JCheckBox jCBIa;
    private javax.swing.JCheckBox jCBVeureFitxes;
    private javax.swing.JLabel jLabelJugador1;
    private javax.swing.JLabel jLabelJugador2;
    private javax.swing.JLabel jLabelJugador3;
    private javax.swing.JLabel jLabelJugador4;
    private javax.swing.JRadioButton jRB2Jug;
    private javax.swing.JRadioButton jRB4Jug;
    // End of variables declaration//GEN-END:variables
}
